### PR TITLE
Adding linter tool (TUM)

### PR DESCRIPTION
**Pull request by swenczowski**
Dear all,

KMT has been experimenting with a linting tool, that checks certain formatting criteria of the newly committed code lines (e.g. line length, white spaces, upper and lower cases of Fortran syntax). Please, feel free to check the rules yourselves in [this file](https://raw.githubusercontent.com/tum-hydromechanics/tum-mglet-base/64e49579b9d079f9cb885fb82899013d8abd2aa6/ci/lint-fortran.py). 

According to my understanding of the rule set and my experience so far, those rules comply well with what we had once defined as a coding standard.

With your permission, I am merging this PR, which will then activate the linter and enforce the code formatting rules. Please, give me your feedback.

Best regards,

Simon

### CODE REVIEW

**Review by hydropott — APPROVED** [review]
Stars: 1/5
Aside from that it's fine.

**Comment by ysakai-tum** [comment]
I'm not an expert of the regular expressions, but are the following rules doing what the corresponding comments say? I'm suspecting that they remove the subroutine/function names afte END SUBROUTINE/FUNCTION because of the "replace None".  

{
        "name": "end_subroutine_2",
        "description": "END SUBROUTINE shall be followed by subroutine name",
        "pattern": r"^ *END *SUBROUTINE *$",
        "replace": None,
    },

    {
        "name": "end_function_2",
        "description": "END FUNCTION shall be followed by function name",
        "pattern": r"^ *END *FUNCTION *$",
        "replace": None,
    },

**Comment by ysakai-tum** [comment]
The same suspicion applies to the following rule as well:

    {
        "name": "end",
        "description": "Use END <construct> instead of END",
        "pattern": r"^ *END *$",
        "replace": None,
    },

**Comment by ysakai-tum** [comment]
The following rules conflict with the style guide we have (or at least I use) to use the spaces around the braces to distinguish functions/subroutines from the array indices.

    {
        "name": "open_parenthesis",
        "description": "Opening parenthesis shall not be followed by a space",
        "pattern": r"\( +(?!&)",
        "replace": "(",
    },
    {
        "name": "close_parenthesis",
        "description": "Closing parenthesis shall not follow a space",
        "pattern": r" +\)",
        "replace": ")",
    },

**Comment by swenczowski** [comment]
> I'm not an expert of the regular expressions, but are the following rules doing what the corresponding comments say? I'm suspecting that they remove the subroutine/function names afte END SUBROUTINE/FUNCTION because of the "replace None".
> 
> { "name": "end_subroutine_2", "description": "END SUBROUTINE shall be followed by subroutine name", "pattern": r"^ *END *SUBROUTINE *$", "replace": None, },
> 
> ```
> {
>     "name": "end_function_2",
>     "description": "END FUNCTION shall be followed by function name",
>     "pattern": r"^ *END *FUNCTION *$",
>     "replace": None,
> },
> ```

That may be a misunderstanding. As I see it, the "replace" refers to how an automated fix would address that issue, when you execute the tool with "--fix". Here, no automated fix would take place. The programmer is urged to add the function name.

**Comment by swenczowski** [comment]
> The following rules conflict with the style guide we have (or at least I use) to use the spaces around the braces to distinguish functions/subroutines from the array indices.
> 
> ```
> {
>     "name": "open_parenthesis",
>     "description": "Opening parenthesis shall not be followed by a space",
>     "pattern": r"\( +(?!&)",
>     "replace": "(",
> },
> {
>     "name": "close_parenthesis",
>     "description": "Closing parenthesis shall not follow a space",
>     "pattern": r" +\)",
>     "replace": ")",
> },
> ```

Yes, that is the rule I personally struggle with the most as well... Shall we adopt it or discuss it with KMT? I do believe that it would be great if the rules were consistent between us and KMT, as otherwise trouble boils up once we try and merge things into master, which happens more than initially expected.

**Comment by ysakai-tum** [comment]
> > I'm not an expert of the regular expressions, but are the following rules doing what the corresponding comments say? I'm suspecting that they remove the subroutine/function names afte END SUBROUTINE/FUNCTION because of the "replace None".
> > { "name": "end_subroutine_2", "description": "END SUBROUTINE shall be followed by subroutine name", "pattern": r"^ *END *SUBROUTINE *$", "replace": None, },
> > ```
> > {
> >     "name": "end_function_2",
> >     "description": "END FUNCTION shall be followed by function name",
> >     "pattern": r"^ *END *FUNCTION *$",
> >     "replace": None,
> > },
> > ```
> 
> That may be a misunderstanding. As I see it, the "replace" refers to how an automated fix would address that issue, when you execute the tool with "--fix". Here, no automated fix would take place. The programmer is urged to add the function name.

Ok, now I see it from the following. Thanks.

    # Then apply rules that apply to the code after stripping comments
    for rule in _rules:
        # The position of the comment marker can change as rules are applied
        pos = comment_pos(line)
        pattern = rule["pattern"]
        replace = rule["replace"]
        if re.search(pattern, line[:pos]):
            if replace is not None:
                line = re.sub(pattern, replace, line[:pos]) + line[pos:]

    return line

**Comment by ysakai-tum** [comment]
> > The following rules conflict with the style guide we have (or at least I use) to use the spaces around the braces to distinguish functions/subroutines from the array indices.
> > ```
> > {
> >     "name": "open_parenthesis",
> >     "description": "Opening parenthesis shall not be followed by a space",
> >     "pattern": r"\( +(?!&)",
> >     "replace": "(",
> > },
> > {
> >     "name": "close_parenthesis",
> >     "description": "Closing parenthesis shall not follow a space",
> >     "pattern": r" +\)",
> >     "replace": ")",
> > },
> > ```
> 
> Yes, that is the rule I personally struggle with the most as well... Shall we adopt it or discuss it with KMT? I do believe that it would be great if the rules were consistent between us and KMT, as otherwise trouble boils up once we try and merge things into master, which happens more than initially expected.

Yes, let's ask their opinion about this rule.

**Pull request merged**
